### ISSUE TITLE
How to show target frame when selecting player and hiding it when not selected. Also, are action bar paging/shift modifiers possible?

### ISSUE THREAD

**Issue by Flashychunk** [albertobeloni/CUI#1]
Hi there,

I have been using your addon and love it, made coming back to wow a lot more enjoyable! I just wanted to ask about two things i've been trying figure out - if that's alright...

**1) "How to show target frame when selecting player and hiding it when not selected"**
I noticed while playing or found that it's great to have the target and player frames hidden. But it is a little difficult specifically with the target frames, to not being able to interact with them/get them to show when you select a player in the open world. Just to inspect other players, check any buffs, while not in a group; and then hide when not selected

I'm not familiar or know how to add macro conditionals to the lua, I have had a tough time looking for this conditional online for this exactly. Would you be able to provide any assistance on being able to change this in the config? 

**2) "Also are action bar paging/shift modifiers possible?"**
The other thing I wanted to ask - is to do with action bar paging and using shift modifiers to change the bar to a different bar, while you're holding down shift, ctrl, or alt. For instance, having your action bar change from bar 1 when not holding shift to when holding shift it change to bar 4 with new buttons. 

Bartender, Elvui and Dominos can do this (provided a screenshot to show what I mean). I wanted to ask if there is a way to achieve this with your addon using macro conditionals in your lua config?  Usually, I see [mod:shift] 6; [mod:ctrl] 5; for example, in custom conditionals in addons like elvui to achieve this result (included a screenshot to show this aswell). 

I would use any of these addons together with yours, but I like what you've done with the action bar, and it gets rid of your stuff if I use both addons.

No worries if there's no way to do this, appreciate any help and thanks again for creating this - **love it!**

<img width="619" alt="bt4" src="https://github.com/albertobeloni/CUI/assets/151573465/485afe11-988c-491c-b68a-6016c22ab5d3">
<img width="900" alt="elvuiabpg" src="https://github.com/albertobeloni/CUI/assets/151573465/003e5c0f-5e86-477d-9871-49906087a297">

**Comment by albertobeloni** [comment]
Any feedback is appreciated. I'm happy that you are enjoying my AddOn. Regarding your questions:

1) For now you can change the following lines in the code:

```lua
function CUI:TargetFrame()
    local condition = "[harm,exists,nodead][help,combat,exists] show; hide"
```

I suggest changing to something like this:

```lua
function CUI:TargetFrame()
    local condition = "[harm,exists,nodead][help,exists] show; hide"
```

I'll move this condition to a variable for ease of configuration in the next release. I'm still trying to find time to learn how to create a configuration screen to improve this process.

2) This one might be trick. I'll have to test how powerful the conditionals are natively. If it is not supported natively I'll have to say it might be too complicated since I'm using the games default bars (frames) which ElvUI and others don't do, they create their own frames to avoid these limitations. Not making any promises but I'll see what I can do.

**Comment by albertobeloni** [comment]
Faster than expected, it is supported natively, example to swap between two bars:

```lua
CUI.actionBar1 = "show;[mod:ctrl] hide"
CUI.actionBar2 = "[mod:ctrl] show; hide"
```

**Comment by Flashychunk** [comment]
Thank you so much! and for responding so quickly. 

Really sorry to bother you again, especially since this is completed - I just got around to entering both, first one works amazing btw <3, but having a little issue with the action bar paging (shift modifier) lua change:

I tried entering the provided lines in the lua, and I'm wondering if I entered it correctly. 

Since it shows and hides the second action bar from hidden/mouseover, but doesn't let me treat it as a separate action bar that I can add abilities to when holding that modifier key i.e. ctrl/shift (this is what I entered in the lua)
<img width="770" alt="actionbarui" src="https://github.com/albertobeloni/CUI/assets/151573465/d1b0bfff-2518-4f88-8e5e-be3022a94ea3">

I thought it might be easier to take a video and show what I'm currently got displayed by adding those changed lines:

https://github.com/albertobeloni/CUI/assets/151573465/8aa092f6-9fca-4a08-84c3-3b9e098e36c5

**Is this the intended effect that is meant to be displayed when holding shift?** 

Because if it is **I might have poorly explained it** without showing what I meant, **which is my bad**. Or I'm currently having some issues with getting it working. I'm not sure, so **I do apologise if I caused any confusion** and if this isn't something that is possible to natively support with your addon then no worries at all :). 

Just in case I poorly explained it, i took a video below to illustrate what I was trying to achieve with the action paging shift modifiers for your addon - using bartender4/elvui thing
(The first action bar Is displayed on no shift - then it switches to the 3rd page/the 4th action bar - when holding shift. - with new abilities on the keys bound to the first action bar) 
(The same for the second action bar I have it so when holding down shift it switches to the 4th page/5th action bar and when not holding shift it just shows action bar 2)
(So, it just temporarily changes bars while holding that modifier key to any of the extra bars that aren't being used)

https://github.com/albertobeloni/CUI/assets/151573465/f654e3cf-eaf9-46cc-9512-bc7443848c03

**Comment by albertobeloni** [comment]
You can achieve the intended effect by positioning one Action Bar on top of the other using Edit Menu and "swap" them using the modifier key. The only thing that might be trickier is the decorations on the Main Action Bar, if you hide the bar it hides everything. You can try just enabling Action Bar 2 on top of the Main Action Bar without hiding the former.

**Comment by albertobeloni** [comment]
BTW, you can update the AddOn. It now have a configuration screen accessible through the options menu or using the command ```/cui```. Easier than editing the code and it should now save your configuration after updating the AddOn.

**Comment by Flashychunk** [comment]
Thank you so much for the help, really appreciate it :)! and the config menu is great!
