### ISSUE TITLE
Clickable links / items in chat

### ISSUE THREAD

**Issue by Bighunternrg** [albertobeloni/CUI#2]
## Interface: 100200
    ## Title: CUI
    ## Notes: World of Warcraft Custom UI
    ## Version: 1.0
    ## Author: Alberto Beloni
    UI.lua

![image](https://github.com/albertobeloni/CUI/assets/151900147/254e4681-e3c7-4a52-83ea-b60e4eb8b6df)

Addons loaded: None, only yours.
Problem: I can't left click Items, Profession links etc.

Disabling your addon resolves the issue, I can then click on links in trade chat / guild chat etc.

**Comment by albertobeloni** [comment]
Thanks for reporting this. I'll take a look as soon as possible.

**Comment by albertobeloni** [comment]
A little lost on this one. I don't hook any scripts on FontStringContainer so it shouldn't mess with the mouseover or click. I'll have to explore a little further if changing the frame parent can break the default behaviour.

**Comment by albertobeloni** [comment]
I just released a new version (v2.0.0) that includes a configuration screen and also removes the functionality that was causing this bug. For now it is fixed but it is not possible anymore to show manipulate just the chat text, at least until I find a better way to implement it.
