### ISSUE TITLE
Error when opening edit mode

### ISSUE THREAD

**Issue by qbarbosa** [albertobeloni/CUI#6]
Hi and thank you for maintaining this!

I have an error when I open edit mode, suggesting me to deactivate CUI.

Here is the log from BugSack : 

```
1x [ADDON_ACTION_FORBIDDEN] L'AddOn 'CUI' a tenté d'appeler la fonction protégée 'TargetUnit()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `TargetUnit'
[string "@FrameXML/EditModeManager.lua"]:1836: in function `RefreshTargetAndFocus'
[string "@FrameXML/EditModeManager.lua"]:1746: in function `OnEditModeEnter'
[string "@FrameXML/EditModeManager.lua"]:186: in function `EnterEditMode'
[string "@FrameXML/EditModeManager.lua"]:211: in function <FrameXML/EditModeManager.lua:209>
[string "=[C]"]: in function `Show'
[string "@FrameXML/UIParent.lua"]:2938: in function `SetUIPanel'
[string "@FrameXML/UIParent.lua"]:2742: in function `ShowUIPanel'
[string "@FrameXML/UIParent.lua"]:2646: in function <FrameXML/UIParent.lua:2642>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/UIParent.lua"]:3248: in function `ShowUIPanel'
[string "*GameMenuFrame.xml:91_OnClick"]:2: in function <[string "*GameMenuFrame.xml:91_OnClick"]:1>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}
```

Tell me if you need other details! Thanks!

**Comment by albertobeloni** [comment]
I'll try to reproduce the error on my side. Can you add some more information, like were you in combat when opening Edit Mode, or entered combat while in Edit Mode?

**Comment by albertobeloni** [comment]
I wasn't able to reproduce the error so far, been playing as usual, opening Edit Mode in combat, outside of combat, etc. I'll need more context to find the source of the error. Were you using any other AddOns?

**Comment by qbarbosa** [comment]
Hi !

I tried to identify the source of the bug but I am not able to reproduce it consistently. I just got it again so I try to provide more details this time: 

**Bug grabber message:**
```
1x [ADDON_ACTION_FORBIDDEN] L'AddOn 'CUI' a tenté d'appeler la fonction protégée 'TargetUnit()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `TargetUnit'
[string "@FrameXML/EditModeManager.lua"]:1836: in function `RefreshTargetAndFocus'
[string "@FrameXML/EditModeManager.lua"]:1746: in function `OnEditModeEnter'
[string "@FrameXML/EditModeManager.lua"]:186: in function `EnterEditMode'
[string "@FrameXML/EditModeManager.lua"]:211: in function <FrameXML/EditModeManager.lua:209>
[string "=[C]"]: in function `Show'
[string "@FrameXML/UIParent.lua"]:2938: in function `SetUIPanel'
[string "@FrameXML/UIParent.lua"]:2742: in function `ShowUIPanel'
[string "@FrameXML/UIParent.lua"]:2646: in function <FrameXML/UIParent.lua:2642>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/UIParent.lua"]:3248: in function `ShowUIPanel'
[string "*GameMenuFrame.xml:91_OnClick"]:2: in function <[string "*GameMenuFrame.xml:91_OnClick"]:1>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}
```

**CUI config :** 
![image](https://github.com/albertobeloni/CUI/assets/16538058/27d9ca91-068c-4fcc-abfa-dc94cbe2e5ff)
![image](https://github.com/albertobeloni/CUI/assets/16538058/ef03f8bc-e693-4949-a599-dab47a360586)
![image](https://github.com/albertobeloni/CUI/assets/16538058/df98d277-3520-453b-b909-ac807f2349d0)
![image](https://github.com/albertobeloni/CUI/assets/16538058/9bfe306f-3020-4582-8c6f-fafd559c02a3)
![image](https://github.com/albertobeloni/CUI/assets/16538058/053f0b4b-83e6-4c49-b13a-2f1ecfb7a2dd)
![image](https://github.com/albertobeloni/CUI/assets/16538058/53c35f34-75d1-4df7-b043-e0d3959b5066)


**Other addons on use:**
- Addon Usage
- AdiBags
- AdvancedInterfaceOptions
- Angry Keystones
- Astral Keys
- Auctionator
- AverageItemLevel
- Battle Pet BreedID
- BigDebuffs
- BugGrabber
- BugSack
- CastCursor
- Clique
- CUI
- DejaCharacterStats
- Details
- HealthBarColor
- Leatrix Maps
- Leatrix Plus
- LoggerHead
- MinimapButtonButton
- Move Tooltip Lite
- Nameplate Scrolling Combat Text
- OmniCC
- OmniCD
- Quartz
- Raider.IO
- Right Click Modifier
- Simulationcraft
- WeakAuras


Also I have observed something weird: with my current settings when I have a target the main action bar is displayed otherwise it is hidden (while I just put `hide` in the config). 
Maybe it is unrelated but since the error message mentions "TargetUnit" I thought it was worth mentioning.

I just saw you published a new version and I updated to it. I hope it fixes the bug somehow.

Thank you for your help!

**Comment by albertobeloni** [comment]
I can't be sure but it might be a conflict with another AddOn, since CUI works with default game frames. Regardless, I'll take another look ASAP.
