### ISSUE TITLE
Lua Error when sending/receiving a chat message

### ISSUE THREAD

**Issue by u8Jj3** [albertobeloni/CUI#7]
Hello,

Since the last addon update, i'm having a lua error when I send/receive a message.

```
Message: Usage: local cbObject = C_Timer.NewTimer(seconds, callback)
Time: Thu Dec 14 18:20:18 2023
Count: 2
Stack: Usage: local cbObject = C_Timer.NewTimer(seconds, callback)
[string "=[C]"]: in function `NewTimer'
[string "@Interface/AddOns/CUI/CUI.lua"]:1261: in function `AddMessage'
[string "@Interface/FrameXML/ChatFrame.lua"]:3993: in function `ChatFrame_MessageEventHandler'
[string "@Interface/FrameXML/ChatFrame.lua"]:3197: in function `ChatFrame_OnEvent'
[string "*FloatingChatFrame.xml:663_OnEvent"]:1: in function <[string "*FloatingChatFrame.xml:663_OnEvent"]:1>

Locals: (*temporary) = "Usage: local cbObject = C_Timer.NewTimer(seconds, callback)"
```

Chat config:

- [x] Enable Chat Module
- [x] Show Chat in Combat
- [x] Show Chat in Instances
- [x] Show Chat on Update
- Update Duration: 5

**Comment by albertobeloni** [comment]
I didn't tested the last release enough, it was full of bugs. I just released a new version of the AddOn under a new name. It is a complete rewrite, much more robust: https://www.curseforge.com/wow/addons/world-of-warcraft-ui
