### ISSUE TITLE
berenaranos UI -  Setting Changes are lost after closing the options window

### ISSUE THREAD

**Issue by Hainroc** [albertobeloni/CUI#8]
Dear Creator,

I saw your UI self-advertisement on reddit and would love to give your UI a try. However, any changes to the UI Settings I make under Options -> AddOns ->  UI are lost once I close the window.

I have removed my Cache, WTF and Interface folder and reset my cvars setting to rule out any interaction issues. 

Can you help me with fixing this issue?

Thanks

Hainroc

**Comment by albertobeloni** [comment]
This version of the AddOn is deprecated. Please download the new [AddOn on CurseForge](https://www.curseforge.com/wow/addons/world-of-warcraft-ui). If the problem occurs with the new version, please report on the [AddOn Issue Tracker](https://github.com/albertobeloni/UI/issues).
